### ISSUE TITLE
exporter.rb:98:in `dig': String does not have #dig method (TypeError)

### ISSUE THREAD

**Issue by dean224** [Shopify/shopify_transporter#149]
#### CAUTION: Do not attach any sensitive information or PII

Please be careful not to include sensitive information in the files because this is a public repository (for example, real customer names, emails and addresses).

#### Problem:
exporter.rb:98:in `dig': String does not have #dig method (TypeError)

**Comment by tpyrohova** [comment]
I have the same problem. Any solution?
