### ISSUE TITLE
Server Side Exception: Allowed Memory Exhausted

### ISSUE THREAD

**Issue by surajreddy** [Shopify/shopify_transporter#15]
Original comment: 

In some cases, the savon is returning an out of memory error, as noticed by @reckerswartz : https://github.com/Shopify/shopify_transporter/issues/8#issuecomment-394832687

Running `ruby orders.rb` is raising:
```
/gems/savon-2.12.0/lib/savon/response.rb:85:in `raise_soap_and_http_errors!': (SOAP-ENV:Server) Allowed memory size of 2147483648 bytes exhausted (tried to allocate 83 bytes) (Savon::SOAPFault)
	from /home/aventum/.rvm/gems/ruby-2.4.0@transporter/gems/savon-2.12.0/lib/savon/response.rb:14:in `initialize'
	from /home/aventum/.rvm/gems/ruby-2.4.0@transporter/gems/savon-2.12.0/lib/savon/operation.rb:72:in `new'
	from /home/aventum/.rvm/gems/ruby-2.4.0@transporter/gems/savon-2.12.0/lib/savon/operation.rb:72:in `create_response'
	from /home/aventum/.rvm/gems/ruby-2.4.0@transporter/gems/savon-2.12.0/lib/savon/operation.rb:58:in `call'
	from /home/aventum/.rvm/gems/ruby-2.4.0@transporter/gems/savon-2.12.0/lib/savon/client.rb:36:in `call'
	from orders.rb:28:in `base_orders'
	from orders.rb:19:in `orders'
	from orders.rb:9:in `run'
	from orders.rb:48:in `<main>'
```

**Comment by surajreddy** [comment]
@reckerswartz this seems to be because the server ran out of memory while generating the data needed for the request: https://magento2.atlassian.net/wiki/spaces/m1wiki/pages/14024846/Allowed+memory+size+exhausted

This seems to happen on the request to generate the list of orders using the `salesOrderList` call.

We are already working on updating the scripts to retrieve a smaller set of orders at a time and be resumable. This will help tremendously with this issue.

Until then, you can make these changes to only retrieve orders for specific dates with code like this:
```ruby
# update the `def soap_client` method in `sample_scripts/third_party_platform_exporting/magento/v1.9/soap_api/transporter_exporter.rb` to:
  def soap_client
    @soap_client ||= Savon.client(
      wsdl: "https://#{required_env_vars['MAGENTO_SOAP_API_HOSTNAME']}/api/v2_soap?wsdl",
      open_timeout: 500,
      read_timeout: 500,
      convert_request_keys_to: :none
    )
  end

# change the `base_orders` and `items_for` methods in `sample_scripts/third_party_platform_exporting/magento/v1.9/soap_api/orders.rb`  to:
  def base_orders
    soap_client.call(
      :sales_order_list,
      message: {
        sessionId: soap_session_id,
        filters: filters.merge(complex_filters),
      }
    ).body[:sales_order_list_response][:result][:item]
  end

  def items_for(order)
    soap_client.call(
      :sales_order_info,
      message: {
        sessionId: soap_session_id,
        orderIncrementId: order[:increment_id],
      }
    ).body[:sales_order_info_response]
  end

  def filters
    {
      filter: {
        item: {
          key: 'store_id',
          value: required_env_vars['MAGENTO_STORE_ID'],
        }
      }
    }
  end

  def complex_filters
    # Change the `from` and `to` values to the dates you want to get orders for
    {
      complex_filter: [
        item: [
          {
            key: 'created_at',
            value: {
                key: 'from',
                value: '2018-05-01 00:00:00',
            }
          },
          {
            key: 'created_at',
            value: {
                key: 'to',
                value: '2018-06-01 00:00:00',
            }
          },
        ]
      ]
    }
  end
```

You can store these files into seperate json outputs:
```
# Set a start and end date in the complex_filters method above to get a subset or orders and then run the script:
ruby orders.rb > magento_orders1.json

# Change the dates to get more orders and then run the script again:
ruby orders.rb > magento_orders2.json

# Change the dates to get more orders and then run the script again:
ruby orders.rb > magento_orders3.json
```

The gem accepts multiple files as input when converting:
```
shopify_transporter convert --config=config.yml --object=customer magento_orders1.json magento_orders2.json magento_orders3.json > shopify_customers.csv
```

**Comment by reckerswartz** [comment]
@surajreddy  after making chaces as per above instruction it is rising another error
```
/home/aventum/.rvm/gems/ruby-2.4.0@transporter/gems/savon-2.12.0/lib/savon/response.rb:85:in `raise_soap_and_http_errors!': (6) Required parameter is missing, for more details see "exception.log". (Savon::SOAPFault)
	from /home/aventum/.rvm/gems/ruby-2.4.0@transporter/gems/savon-2.12.0/lib/savon/response.rb:14:in `initialize'
	from /home/aventum/.rvm/gems/ruby-2.4.0@transporter/gems/savon-2.12.0/lib/savon/operation.rb:72:in `new'
	from /home/aventum/.rvm/gems/ruby-2.4.0@transporter/gems/savon-2.12.0/lib/savon/operation.rb:72:in `create_response'
	from /home/aventum/.rvm/gems/ruby-2.4.0@transporter/gems/savon-2.12.0/lib/savon/operation.rb:58:in `call'
	from /home/aventum/.rvm/gems/ruby-2.4.0@transporter/gems/savon-2.12.0/lib/savon/client.rb:36:in `call'
	from /home/aventum/workspace/shopify_transporter/sample_scripts/third_party_platform_exporting/magento/v1.9/soap_api/transporter_exporter.rb:41:in `soap_session_id'
	from orders.rb:30:in `base_orders'
	from orders.rb:19:in `orders'
	from orders.rb:9:in `run'
	from orders.rb:83:in `<main>'

```

**Comment by surajreddy** [comment]
@reckerswartz this is likely because one of the parameters does not have the right casing.

Can you confirm that the casing of these request parameters is correct in the `def soap_session_id` method?
```
      message: {
        username: required_env_vars['MAGENTO_SOAP_API_USERNAME'],
        apiKey: required_env_vars['MAGENTO_SOAP_API_KEY'],
      }
```

The apiKey parameter used to be `api_key:` but now needs to be `apiKey`.

**Comment by reckerswartz** [comment]
@surajreddy forget to make that change but another issue pop up
`ruby orders.rb`
getting
`sesion_id: 7b2e2c510fbxxxxxxxf98xx1cb4e1758d49c`
```
/home/aventum/.rvm/gems/ruby-2.4.0@transporter/gems/savon-2.12.0/lib/savon/response.rb:85:in `raise_soap_and_http_errors!': (5) Session expired. Try to relogin. (Savon::SOAPFault)
	from /home/aventum/.rvm/gems/ruby-2.4.0@transporter/gems/savon-2.12.0/lib/savon/response.rb:14:in `initialize'
	from /home/aventum/.rvm/gems/ruby-2.4.0@transporter/gems/savon-2.12.0/lib/savon/operation.rb:72:in `new'
	from /home/aventum/.rvm/gems/ruby-2.4.0@transporter/gems/savon-2.12.0/lib/savon/operation.rb:72:in `create_response'
	from /home/aventum/.rvm/gems/ruby-2.4.0@transporter/gems/savon-2.12.0/lib/savon/operation.rb:58:in `call'
	from /home/aventum/.rvm/gems/ruby-2.4.0@transporter/gems/savon-2.12.0/lib/savon/client.rb:36:in `call'
	from orders.rb:28:in `base_orders'
	from orders.rb:19:in `orders'
	from orders.rb:9:in `run'
	from orders.rb:86:in `<main>'
```

**Comment by surajreddy** [comment]
@reckerswartz this is an error from the Magento instance. It usually means that the session id has expired by the time the code is making a second request. If you're using the script as is, it shouldn't happen as the script generates a new session every time it is run.

If it is still happening, then I suggest checking the session settings on the magento instance - maybe the session is set to expire very fast.

**Comment by surajreddy** [comment]
Closing this because of inactivity.

For memory issues I would suggest trying some of the code in the https://github.com/Shopify/shopify_transporter/tree/extraction-scripts-by-daterange branch. The code in this branch extracts data in batches and should reduce the memory constraints needed. There is a readme for using the code in the branch at https://github.com/Shopify/shopify_transporter/blob/extraction-scripts-by-daterange/sample_scripts/third_party_platform_exporting/magento/v1.9/soap_api/README.md

This will be merged with the primary tool soon, but it needs some more work before it can be fully integrated.
